### PR TITLE
Irregular section

### PR DESCRIPTION
**Pull request by alexiusacademia**
Hello Ben. I tried to modify the Irregular Section part. I'm not sure if it's what you're looking for but i gave it a shot anyway. Hope you'll like it.

### CODE REVIEW

**Comment by benjiyamin** [comment]
Hey @alexiusacademia thanks for the Pull Request! It looks good so far. I'm gradually looking through it this week to see if I catch anything that jumps out. A few things I saw off the bat I think we should address before merging:

1. I've been documenting everything by the [Google Docstring Format](http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html), so we should match that to stay consistent. You can reference some of the other modules as a good go-by for formatting.

2. According to the unit tests Travis-CI ran, some of the code isn't adhering to [PEP-8](https://www.python.org/dev/peps/pep-0008/). [Here's the current build from your Pull Request](https://travis-ci.org/benjiyamin/pyflo/builds/172216263). It looks like the the lines it detected are:
    - [ ] ./pyflo/sections.py:214:1: W293 blank line contains whitespace
    - [ ] ./pyflo/sections.py:224:1: W293 blank line contains whitespace
    - [ ] ./pyflo/sections.py:237:101: E501 line too long (115 > 100 characters)
    - [ ] ./pyflo/sections.py:254:1: W293 blank line contains whitespace
    - [ ] ./pyflo/sections.py:255:1: W293 blank line contains whitespace
    - [ ] ./pyflo/sections.py:256:5: E303 too many blank lines (2)
    - [ ] ./pyflo/sections.py:263:1: W293 blank line contains whitespace
    - [ ] ./pyflo/sections.py:265:26: E261 at least two spaces before inline comment
    - [ ] ./pyflo/sections.py:273:1: W293 blank line contains whitespace
    - [ ] ./pyflo/sections.py:289:1: W293 blank line contains whitespace
    - [ ] ./pyflo/sections.py:304:1: W293 blank line contains whitespace
    - [ ] ./pyflo/sections.py:315:36: E261 at least two spaces before inline comment
    - [ ] ./pyflo/sections.py:325:1: E265 block comment should start with '# '
   - [ ] ./pyflo/sections.py:330:22: W292 no newline at end of file

    I'm not sure if your current repo has the [pep8 unittest](https://github.com/benjiyamin/pyflo/blob/master/tests/test_pep8.py) I included later, so you may need to `git pull` or `git merge` to grab it

3. I'm adding ".DS_Store" to the repo's .gitignore file so that those files aren't included with the Pull Request. You may need to `git pull` or `git merge` to see the change and update the request.

4. For the `get_lowest_elev` method, are "points" supposed to be a parameter? Or is it supposed to reference the objects `self.points` property? I may be wrong, but just double checking. For example:
    ```python

        def get_lowest_elev(self):
            elevs = []                  # List of elevations (ordinates)
            lowest = 0                  # Initial value of lowest
            for point in self.points:
                elevs.append(point[1])  # Iterate through the points and collect the ordinates
            for i in range(len(elevs)): # Find the lowest in the list of ordinates
                if i == len(elevs):
                    break
                if elevs[i] < lowest:
                    lowest = elevs[i]
                else:
                    lowest = lowest
            return lowest
    ```

5. Can you also add some unit tests for the Irregular sections in the [test](https://github.com/benjiyamin/pyflo/tree/master/tests) folder? We might as well test it now. I can help come with a few as well if you want.

**Comment by benjiyamin** [comment]
fixes #1

**Comment by alexiusacademia** [comment]
Hi. I forgot to mention this is my first time collaborating. So thanks for the support and patience. I didn't used pep8 inspection during the time I wrote those methods. But I hope I made it right this time. Happy to collaborate with you.

**Comment by benjiyamin** [comment]
@alexiusacademia no worries. I've merge your changes. Check it out to make sure everything is good :smile:

**Comment by alexiusacademia** [comment]
Is it a good idea to implement a guy for pyflo?

**Comment by benjiyamin** [comment]
@alexiusacademia what do you mean?

**Comment by alexiusacademia** [comment]
Oh my bad. I mean GUI..

**Pull request merged**
